'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace weather
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://tempuri.org/", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="weather.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Generating message contract since element name NTTFilesFolder from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DownloadAPEXFolder", ReplyAction:="*")>  _
        Function DownloadAPEXFolder(ByVal request As weather.DownloadAPEXFolderRequest) As weather.DownloadAPEXFolderResponse
        
        'CODEGEN: Generating message contract since element name path from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetWeather", ReplyAction:="*")>  _
        Function GetWeather(ByVal request As weather.GetWeatherRequest) As weather.GetWeatherResponse
        
        'CODEGEN: Generating message contract since element name loc from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Create_wp1_from_weather", ReplyAction:="*")>  _
        Function Create_wp1_from_weather(ByVal request As weather.Create_wp1_from_weatherRequest) As weather.Create_wp1_from_weatherResponse
        
        'CODEGEN: Generating message contract since element name path from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getHU", ReplyAction:="*")>  _
        Function getHU(ByVal request As weather.getHURequest) As weather.getHUResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/jdt", ReplyAction:="*")>  _
        Function jdt(ByVal i As Short, ByVal m As Short, ByVal nt As Single) As Short
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DownloadAPEXFolderRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DownloadAPEXFolder", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.DownloadAPEXFolderRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.DownloadAPEXFolderRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DownloadAPEXFolderRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public NTTFilesFolder As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public session1 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public type As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal NTTFilesFolder As String, ByVal session1 As String, ByVal type As String)
            MyBase.New
            Me.NTTFilesFolder = NTTFilesFolder
            Me.session1 = session1
            Me.type = type
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DownloadAPEXFolderResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DownloadAPEXFolderResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.DownloadAPEXFolderResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.DownloadAPEXFolderResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DownloadAPEXFolderResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DownloadAPEXFolderResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DownloadAPEXFolderResult As String)
            MyBase.New
            Me.DownloadAPEXFolderResult = DownloadAPEXFolderResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetWeatherRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetWeather", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.GetWeatherRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.GetWeatherRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetWeatherRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public path As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal path As String)
            MyBase.New
            Me.path = path
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetWeatherResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetWeatherResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.GetWeatherResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.GetWeatherResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetWeatherResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetWeatherResult As weather.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetWeatherResult As weather.ArrayOfString)
            MyBase.New
            Me.GetWeatherResult = GetWeatherResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Create_wp1_from_weatherRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Create_wp1_from_weather", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.Create_wp1_from_weatherRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.Create_wp1_from_weatherRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Create_wp1_from_weatherRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public loc As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public wp1name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public controlvalue5 As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public pgm As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal loc As String, ByVal wp1name As String, ByVal controlvalue5 As Integer, ByVal pgm As String)
            MyBase.New
            Me.loc = loc
            Me.wp1name = wp1name
            Me.controlvalue5 = controlvalue5
            Me.pgm = pgm
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Create_wp1_from_weatherResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Create_wp1_from_weatherResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.Create_wp1_from_weatherResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.Create_wp1_from_weatherResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Create_wp1_from_weatherResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Create_wp1_from_weatherResult As weather.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Create_wp1_from_weatherResult As weather.ArrayOfString)
            MyBase.New
            Me.Create_wp1_from_weatherResult = Create_wp1_from_weatherResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getHURequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getHU", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.getHURequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.getHURequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getHURequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public crop As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nlat As Single
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public nlon As Single
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public plantingJulianDay As UShort
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public path As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal crop As Short, ByVal nlat As Single, ByVal nlon As Single, ByVal plantingJulianDay As UShort, ByVal path As String)
            MyBase.New
            Me.crop = crop
            Me.nlat = nlat
            Me.nlon = nlon
            Me.plantingJulianDay = plantingJulianDay
            Me.path = path
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getHUResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getHUResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As weather.getHUResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As weather.getHUResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getHUResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public getHUResult As Single
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getHUResult As Single)
            MyBase.New
            Me.getHUResult = getHUResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits weather.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of weather.ServiceSoap)
        Implements weather.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function weather_ServiceSoap_DownloadAPEXFolder(ByVal request As weather.DownloadAPEXFolderRequest) As weather.DownloadAPEXFolderResponse Implements weather.ServiceSoap.DownloadAPEXFolder
            Return MyBase.Channel.DownloadAPEXFolder(request)
        End Function
        
        Public Function DownloadAPEXFolder(ByVal NTTFilesFolder As String, ByVal session1 As String, ByVal type As String) As String
            Dim inValue As weather.DownloadAPEXFolderRequest = New weather.DownloadAPEXFolderRequest()
            inValue.Body = New weather.DownloadAPEXFolderRequestBody()
            inValue.Body.NTTFilesFolder = NTTFilesFolder
            inValue.Body.session1 = session1
            inValue.Body.type = type
            Dim retVal As weather.DownloadAPEXFolderResponse = CType(Me,weather.ServiceSoap).DownloadAPEXFolder(inValue)
            Return retVal.Body.DownloadAPEXFolderResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function weather_ServiceSoap_GetWeather(ByVal request As weather.GetWeatherRequest) As weather.GetWeatherResponse Implements weather.ServiceSoap.GetWeather
            Return MyBase.Channel.GetWeather(request)
        End Function
        
        Public Function GetWeather(ByVal path As String) As weather.ArrayOfString
            Dim inValue As weather.GetWeatherRequest = New weather.GetWeatherRequest()
            inValue.Body = New weather.GetWeatherRequestBody()
            inValue.Body.path = path
            Dim retVal As weather.GetWeatherResponse = CType(Me,weather.ServiceSoap).GetWeather(inValue)
            Return retVal.Body.GetWeatherResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function weather_ServiceSoap_Create_wp1_from_weather(ByVal request As weather.Create_wp1_from_weatherRequest) As weather.Create_wp1_from_weatherResponse Implements weather.ServiceSoap.Create_wp1_from_weather
            Return MyBase.Channel.Create_wp1_from_weather(request)
        End Function
        
        Public Function Create_wp1_from_weather(ByVal loc As String, ByVal wp1name As String, ByVal controlvalue5 As Integer, ByVal pgm As String) As weather.ArrayOfString
            Dim inValue As weather.Create_wp1_from_weatherRequest = New weather.Create_wp1_from_weatherRequest()
            inValue.Body = New weather.Create_wp1_from_weatherRequestBody()
            inValue.Body.loc = loc
            inValue.Body.wp1name = wp1name
            inValue.Body.controlvalue5 = controlvalue5
            inValue.Body.pgm = pgm
            Dim retVal As weather.Create_wp1_from_weatherResponse = CType(Me,weather.ServiceSoap).Create_wp1_from_weather(inValue)
            Return retVal.Body.Create_wp1_from_weatherResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function weather_ServiceSoap_getHU(ByVal request As weather.getHURequest) As weather.getHUResponse Implements weather.ServiceSoap.getHU
            Return MyBase.Channel.getHU(request)
        End Function
        
        Public Function getHU(ByVal crop As Short, ByVal nlat As Single, ByVal nlon As Single, ByVal plantingJulianDay As UShort, ByVal path As String) As Single
            Dim inValue As weather.getHURequest = New weather.getHURequest()
            inValue.Body = New weather.getHURequestBody()
            inValue.Body.crop = crop
            inValue.Body.nlat = nlat
            inValue.Body.nlon = nlon
            inValue.Body.plantingJulianDay = plantingJulianDay
            inValue.Body.path = path
            Dim retVal As weather.getHUResponse = CType(Me,weather.ServiceSoap).getHU(inValue)
            Return retVal.Body.getHUResult
        End Function
        
        Public Function jdt(ByVal i As Short, ByVal m As Short, ByVal nt As Single) As Short Implements weather.ServiceSoap.jdt
            Return MyBase.Channel.jdt(i, m, nt)
        End Function
    End Class
End Namespace
