'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace NTTBlock
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="NTTBlock.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DownloadAPEXFolder", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DownloadAPEXFolder(ByVal NTTFilesFolder As String, ByVal session1 As String, ByVal type As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetStates", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetStates() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCounties", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCounties(ByVal state As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCounty", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCounty(ByVal state As String, ByVal county As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRecord", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetRecord(ByVal sSql As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSoilRecord", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetSoilRecord(ByVal sSql As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSSA", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetSSA(ByVal county_code As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSoils", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetSoils(ByVal ssa As String, ByVal county_code As String, ByVal txtMaxSlope As String, ByVal txtSoilsPercentage As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetWeather", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetWeather(ByVal path As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Create_wp1_from_weather", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Create_wp1_from_weather(ByVal loc As String, ByVal wp1name As String, ByVal controlvalue5 As Integer, ByVal pgm As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getHU", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getHU(ByVal crop As Short, ByVal nlat As Single, ByVal nlon As Single, ByVal plantingJulianDay As UShort, ByVal path As String) As Single
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/jdt", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function jdt(ByVal i As Short, ByVal m As Short, ByVal nt As Single) As Short
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetWeatherfileName", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetWeatherfileName(ByVal nlat As Single, ByVal nlon As Single, ByVal latLess As Single, ByVal latPlus As Single, ByVal lonLess As Single, ByVal lonPlus As Single) As System.Data.DataTable
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits NTTBlock.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of NTTBlock.ServiceSoap)
        Implements NTTBlock.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function DownloadAPEXFolder(ByVal NTTFilesFolder As String, ByVal session1 As String, ByVal type As String) As String Implements NTTBlock.ServiceSoap.DownloadAPEXFolder
            Return MyBase.Channel.DownloadAPEXFolder(NTTFilesFolder, session1, type)
        End Function
        
        Public Function GetStates() As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetStates
            Return MyBase.Channel.GetStates
        End Function
        
        Public Function GetCounties(ByVal state As String) As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetCounties
            Return MyBase.Channel.GetCounties(state)
        End Function
        
        Public Function GetCounty(ByVal state As String, ByVal county As String) As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetCounty
            Return MyBase.Channel.GetCounty(state, county)
        End Function
        
        Public Function GetRecord(ByVal sSql As String) As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetRecord
            Return MyBase.Channel.GetRecord(sSql)
        End Function
        
        Public Function GetSoilRecord(ByVal sSql As String) As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetSoilRecord
            Return MyBase.Channel.GetSoilRecord(sSql)
        End Function
        
        Public Function GetSSA(ByVal county_code As String) As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetSSA
            Return MyBase.Channel.GetSSA(county_code)
        End Function
        
        Public Function GetSoils(ByVal ssa As String, ByVal county_code As String, ByVal txtMaxSlope As String, ByVal txtSoilsPercentage As String) As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetSoils
            Return MyBase.Channel.GetSoils(ssa, county_code, txtMaxSlope, txtSoilsPercentage)
        End Function
        
        Public Function GetWeather(ByVal path As String) As String() Implements NTTBlock.ServiceSoap.GetWeather
            Return MyBase.Channel.GetWeather(path)
        End Function
        
        Public Function Create_wp1_from_weather(ByVal loc As String, ByVal wp1name As String, ByVal controlvalue5 As Integer, ByVal pgm As String) As String() Implements NTTBlock.ServiceSoap.Create_wp1_from_weather
            Return MyBase.Channel.Create_wp1_from_weather(loc, wp1name, controlvalue5, pgm)
        End Function
        
        Public Function getHU(ByVal crop As Short, ByVal nlat As Single, ByVal nlon As Single, ByVal plantingJulianDay As UShort, ByVal path As String) As Single Implements NTTBlock.ServiceSoap.getHU
            Return MyBase.Channel.getHU(crop, nlat, nlon, plantingJulianDay, path)
        End Function
        
        Public Function jdt(ByVal i As Short, ByVal m As Short, ByVal nt As Single) As Short Implements NTTBlock.ServiceSoap.jdt
            Return MyBase.Channel.jdt(i, m, nt)
        End Function
        
        Public Function GetWeatherfileName(ByVal nlat As Single, ByVal nlon As Single, ByVal latLess As Single, ByVal latPlus As Single, ByVal lonLess As Single, ByVal lonPlus As Single) As System.Data.DataTable Implements NTTBlock.ServiceSoap.GetWeatherfileName
            Return MyBase.Channel.GetWeatherfileName(nlat, nlon, latLess, latPlus, lonLess, lonPlus)
        End Function
    End Class
End Namespace
